services:
  app:
    image: jefffawsdevday1.jfrog.io/workshop-docker/ecs-docker-compose-workshop-app:${run_number}
    restart: always
    ports:
      - 80:80
    networks:
      - appnet
networks:
  appnet:
